//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codigo2024Clase32NetFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int IdDetalle { get; set; }
        public int IdCabecera { get; set; }
        public string Producto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Cabecera Cabecera { get; set; }
    }
}
